//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMefWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PIP", Namespace="http://tempuri.org/")]
    public partial class PIP : object
    {
        
        private string CodigoField;
        
        private string CodigoUnicoField;
        
        private string EstadoField;
        
        private string NombreField;
        
        private string FechaRegistroField;
        
        private string TipoCadenaFuncField;
        
        private string FuncionCodigoField;
        
        private string ProgramaCodigoField;
        
        private string SubprogramaCodigoField;
        
        private string FuncionField;
        
        private string ProgramaField;
        
        private string SubprogramaField;
        
        private string UnidadFormuladoraField;
        
        private string UnidadFormuladoraCodigoField;
        
        private string UnidadUEIField;
        
        private string UnidadUEICodigoField;
        
        private string UnidadOPMIField;
        
        private string UnidadOPMICodigoField;
        
        private string NivelGobiernoField;
        
        private string SectorField;
        
        private string SectorCodigoField;
        
        private string PliegoField;
        
        private string PliegoCodigoField;
        
        private string EvaluadoraField;
        
        private string EvaluadoraCodigoField;
        
        private string EjecutoraField;
        
        private string EjecutoraCodigoField;
        
        private string SituacionField;
        
        private string UltimoEstudioField;
        
        private string EstadoUltimoEstudioField;
        
        private string NivelEstudioField;
        
        private System.Nullable<decimal> BeneficiarioField;
        
        private string ConglomeradoCodigoField;
        
        private string FuenteFinanciamientoField;
        
        private System.Nullable<decimal> MontoAlternativaField;
        
        private System.Nullable<decimal> MontoReformuladoField;
        
        private System.Nullable<decimal> MontoF15Field;
        
        private System.Nullable<decimal> MontoF16Field;
        
        private System.Nullable<decimal> MontoLaudoField;
        
        private System.Nullable<decimal> MontoCartaFianzaField;
        
        private System.Nullable<decimal> CostoActualizadoField;
        
        private System.Nullable<decimal> PIMField;
        
        private System.Nullable<decimal> PIAField;
        
        private System.Nullable<decimal> DevengadoAcumuladoField;
        
        private System.Nullable<decimal> DevengadoAnioActualField;
        
        private string DesTipoFormatoField;
        
        private string FlagExpedienteTecnicoField;
        
        private string AnioViabilidadField;
        
        private string FechaViabilidadField;
        
        private string ActualizacionField;
        
        private int NumeroConvenioField;
        
        private string EncarganteConvenioField;
        
        private string NombreConglomeradoField;
        
        private string NombreProgramaInversionField;
        
        private string ModalidadEjecucionField;
        
        private string MarcoField;
        
        private string ConInformeCierreField;
        
        private string IncluidoPMIField;
        
        private string IncluidoPMIEjecucionField;
        
        private string DescripcionCierreField;
        
        private string FlagEtapasField;
        
        private ApiMefWS.ProyectoLocalizacion[] listalocalizacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodigoUnico
        {
            get
            {
                return this.CodigoUnicoField;
            }
            set
            {
                this.CodigoUnicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TipoCadenaFunc
        {
            get
            {
                return this.TipoCadenaFuncField;
            }
            set
            {
                this.TipoCadenaFuncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FuncionCodigo
        {
            get
            {
                return this.FuncionCodigoField;
            }
            set
            {
                this.FuncionCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ProgramaCodigo
        {
            get
            {
                return this.ProgramaCodigoField;
            }
            set
            {
                this.ProgramaCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SubprogramaCodigo
        {
            get
            {
                return this.SubprogramaCodigoField;
            }
            set
            {
                this.SubprogramaCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Funcion
        {
            get
            {
                return this.FuncionField;
            }
            set
            {
                this.FuncionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Programa
        {
            get
            {
                return this.ProgramaField;
            }
            set
            {
                this.ProgramaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Subprograma
        {
            get
            {
                return this.SubprogramaField;
            }
            set
            {
                this.SubprogramaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string UnidadFormuladora
        {
            get
            {
                return this.UnidadFormuladoraField;
            }
            set
            {
                this.UnidadFormuladoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string UnidadFormuladoraCodigo
        {
            get
            {
                return this.UnidadFormuladoraCodigoField;
            }
            set
            {
                this.UnidadFormuladoraCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string UnidadUEI
        {
            get
            {
                return this.UnidadUEIField;
            }
            set
            {
                this.UnidadUEIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string UnidadUEICodigo
        {
            get
            {
                return this.UnidadUEICodigoField;
            }
            set
            {
                this.UnidadUEICodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string UnidadOPMI
        {
            get
            {
                return this.UnidadOPMIField;
            }
            set
            {
                this.UnidadOPMIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string UnidadOPMICodigo
        {
            get
            {
                return this.UnidadOPMICodigoField;
            }
            set
            {
                this.UnidadOPMICodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string NivelGobierno
        {
            get
            {
                return this.NivelGobiernoField;
            }
            set
            {
                this.NivelGobiernoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Sector
        {
            get
            {
                return this.SectorField;
            }
            set
            {
                this.SectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string SectorCodigo
        {
            get
            {
                return this.SectorCodigoField;
            }
            set
            {
                this.SectorCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Pliego
        {
            get
            {
                return this.PliegoField;
            }
            set
            {
                this.PliegoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string PliegoCodigo
        {
            get
            {
                return this.PliegoCodigoField;
            }
            set
            {
                this.PliegoCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Evaluadora
        {
            get
            {
                return this.EvaluadoraField;
            }
            set
            {
                this.EvaluadoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string EvaluadoraCodigo
        {
            get
            {
                return this.EvaluadoraCodigoField;
            }
            set
            {
                this.EvaluadoraCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Ejecutora
        {
            get
            {
                return this.EjecutoraField;
            }
            set
            {
                this.EjecutoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string EjecutoraCodigo
        {
            get
            {
                return this.EjecutoraCodigoField;
            }
            set
            {
                this.EjecutoraCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string Situacion
        {
            get
            {
                return this.SituacionField;
            }
            set
            {
                this.SituacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string UltimoEstudio
        {
            get
            {
                return this.UltimoEstudioField;
            }
            set
            {
                this.UltimoEstudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string EstadoUltimoEstudio
        {
            get
            {
                return this.EstadoUltimoEstudioField;
            }
            set
            {
                this.EstadoUltimoEstudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string NivelEstudio
        {
            get
            {
                return this.NivelEstudioField;
            }
            set
            {
                this.NivelEstudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public System.Nullable<decimal> Beneficiario
        {
            get
            {
                return this.BeneficiarioField;
            }
            set
            {
                this.BeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string ConglomeradoCodigo
        {
            get
            {
                return this.ConglomeradoCodigoField;
            }
            set
            {
                this.ConglomeradoCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string FuenteFinanciamiento
        {
            get
            {
                return this.FuenteFinanciamientoField;
            }
            set
            {
                this.FuenteFinanciamientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public System.Nullable<decimal> MontoAlternativa
        {
            get
            {
                return this.MontoAlternativaField;
            }
            set
            {
                this.MontoAlternativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public System.Nullable<decimal> MontoReformulado
        {
            get
            {
                return this.MontoReformuladoField;
            }
            set
            {
                this.MontoReformuladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public System.Nullable<decimal> MontoF15
        {
            get
            {
                return this.MontoF15Field;
            }
            set
            {
                this.MontoF15Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public System.Nullable<decimal> MontoF16
        {
            get
            {
                return this.MontoF16Field;
            }
            set
            {
                this.MontoF16Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public System.Nullable<decimal> MontoLaudo
        {
            get
            {
                return this.MontoLaudoField;
            }
            set
            {
                this.MontoLaudoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=39)]
        public System.Nullable<decimal> MontoCartaFianza
        {
            get
            {
                return this.MontoCartaFianzaField;
            }
            set
            {
                this.MontoCartaFianzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=40)]
        public System.Nullable<decimal> CostoActualizado
        {
            get
            {
                return this.CostoActualizadoField;
            }
            set
            {
                this.CostoActualizadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=41)]
        public System.Nullable<decimal> PIM
        {
            get
            {
                return this.PIMField;
            }
            set
            {
                this.PIMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=42)]
        public System.Nullable<decimal> PIA
        {
            get
            {
                return this.PIAField;
            }
            set
            {
                this.PIAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=43)]
        public System.Nullable<decimal> DevengadoAcumulado
        {
            get
            {
                return this.DevengadoAcumuladoField;
            }
            set
            {
                this.DevengadoAcumuladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=44)]
        public System.Nullable<decimal> DevengadoAnioActual
        {
            get
            {
                return this.DevengadoAnioActualField;
            }
            set
            {
                this.DevengadoAnioActualField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string DesTipoFormato
        {
            get
            {
                return this.DesTipoFormatoField;
            }
            set
            {
                this.DesTipoFormatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string FlagExpedienteTecnico
        {
            get
            {
                return this.FlagExpedienteTecnicoField;
            }
            set
            {
                this.FlagExpedienteTecnicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string AnioViabilidad
        {
            get
            {
                return this.AnioViabilidadField;
            }
            set
            {
                this.AnioViabilidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string FechaViabilidad
        {
            get
            {
                return this.FechaViabilidadField;
            }
            set
            {
                this.FechaViabilidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string Actualizacion
        {
            get
            {
                return this.ActualizacionField;
            }
            set
            {
                this.ActualizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=50)]
        public int NumeroConvenio
        {
            get
            {
                return this.NumeroConvenioField;
            }
            set
            {
                this.NumeroConvenioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string EncarganteConvenio
        {
            get
            {
                return this.EncarganteConvenioField;
            }
            set
            {
                this.EncarganteConvenioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string NombreConglomerado
        {
            get
            {
                return this.NombreConglomeradoField;
            }
            set
            {
                this.NombreConglomeradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string NombreProgramaInversion
        {
            get
            {
                return this.NombreProgramaInversionField;
            }
            set
            {
                this.NombreProgramaInversionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string ModalidadEjecucion
        {
            get
            {
                return this.ModalidadEjecucionField;
            }
            set
            {
                this.ModalidadEjecucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string Marco
        {
            get
            {
                return this.MarcoField;
            }
            set
            {
                this.MarcoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string ConInformeCierre
        {
            get
            {
                return this.ConInformeCierreField;
            }
            set
            {
                this.ConInformeCierreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=57)]
        public string IncluidoPMI
        {
            get
            {
                return this.IncluidoPMIField;
            }
            set
            {
                this.IncluidoPMIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=58)]
        public string IncluidoPMIEjecucion
        {
            get
            {
                return this.IncluidoPMIEjecucionField;
            }
            set
            {
                this.IncluidoPMIEjecucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string DescripcionCierre
        {
            get
            {
                return this.DescripcionCierreField;
            }
            set
            {
                this.DescripcionCierreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=60)]
        public string FlagEtapas
        {
            get
            {
                return this.FlagEtapasField;
            }
            set
            {
                this.FlagEtapasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=61)]
        public ApiMefWS.ProyectoLocalizacion[] listalocalizacion
        {
            get
            {
                return this.listalocalizacionField;
            }
            set
            {
                this.listalocalizacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProyectoLocalizacion", Namespace="http://tempuri.org/")]
    public partial class ProyectoLocalizacion : object
    {
        
        private decimal CodigoField;
        
        private string DepartamentoField;
        
        private string ProvinciaField;
        
        private string DistritoField;
        
        private string CentroPobladoField;
        
        private string UbigeoField;
        
        private System.Nullable<decimal> latitudField;
        
        private System.Nullable<decimal> longitudField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CentroPoblado
        {
            get
            {
                return this.CentroPobladoField;
            }
            set
            {
                this.CentroPobladoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ubigeo
        {
            get
            {
                return this.UbigeoField;
            }
            set
            {
                this.UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> latitud
        {
            get
            {
                return this.latitudField;
            }
            set
            {
                this.latitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> longitud
        {
            get
            {
                return this.longitudField;
            }
            set
            {
                this.longitudField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiMefWS.wsPCMSoap")]
    public interface wsPCMSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPip", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiMefWS.GetPipResponse> GetPipAsync(ApiMefWS.GetPipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPipLocalizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ApiMefWS.GetPipLocalizacionResponse> GetPipLocalizacionAsync(ApiMefWS.GetPipLocalizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPipRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPip", Namespace="http://tempuri.org/", Order=0)]
        public ApiMefWS.GetPipRequestBody Body;
        
        public GetPipRequest()
        {
        }
        
        public GetPipRequest(ApiMefWS.GetPipRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPipRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public GetPipRequestBody()
        {
        }
        
        public GetPipRequestBody(string codigo)
        {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPipResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPipResponse", Namespace="http://tempuri.org/", Order=0)]
        public ApiMefWS.GetPipResponseBody Body;
        
        public GetPipResponse()
        {
        }
        
        public GetPipResponse(ApiMefWS.GetPipResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPipResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApiMefWS.PIP[] GetPipResult;
        
        public GetPipResponseBody()
        {
        }
        
        public GetPipResponseBody(ApiMefWS.PIP[] GetPipResult)
        {
            this.GetPipResult = GetPipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPipLocalizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPipLocalizacion", Namespace="http://tempuri.org/", Order=0)]
        public ApiMefWS.GetPipLocalizacionRequestBody Body;
        
        public GetPipLocalizacionRequest()
        {
        }
        
        public GetPipLocalizacionRequest(ApiMefWS.GetPipLocalizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPipLocalizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public GetPipLocalizacionRequestBody()
        {
        }
        
        public GetPipLocalizacionRequestBody(string codigo)
        {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPipLocalizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPipLocalizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ApiMefWS.GetPipLocalizacionResponseBody Body;
        
        public GetPipLocalizacionResponse()
        {
        }
        
        public GetPipLocalizacionResponse(ApiMefWS.GetPipLocalizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPipLocalizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApiMefWS.ProyectoLocalizacion[] GetPipLocalizacionResult;
        
        public GetPipLocalizacionResponseBody()
        {
        }
        
        public GetPipLocalizacionResponseBody(ApiMefWS.ProyectoLocalizacion[] GetPipLocalizacionResult)
        {
            this.GetPipLocalizacionResult = GetPipLocalizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsPCMSoapChannel : ApiMefWS.wsPCMSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsPCMSoapClient : System.ServiceModel.ClientBase<ApiMefWS.wsPCMSoap>, ApiMefWS.wsPCMSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsPCMSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsPCMSoapClient.GetBindingForEndpoint(endpointConfiguration), wsPCMSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPCMSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsPCMSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPCMSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsPCMSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsPCMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiMefWS.GetPipResponse> ApiMefWS.wsPCMSoap.GetPipAsync(ApiMefWS.GetPipRequest request)
        {
            return base.Channel.GetPipAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiMefWS.GetPipResponse> GetPipAsync(string codigo)
        {
            ApiMefWS.GetPipRequest inValue = new ApiMefWS.GetPipRequest();
            inValue.Body = new ApiMefWS.GetPipRequestBody();
            inValue.Body.codigo = codigo;
            return ((ApiMefWS.wsPCMSoap)(this)).GetPipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApiMefWS.GetPipLocalizacionResponse> ApiMefWS.wsPCMSoap.GetPipLocalizacionAsync(ApiMefWS.GetPipLocalizacionRequest request)
        {
            return base.Channel.GetPipLocalizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApiMefWS.GetPipLocalizacionResponse> GetPipLocalizacionAsync(string codigo)
        {
            ApiMefWS.GetPipLocalizacionRequest inValue = new ApiMefWS.GetPipLocalizacionRequest();
            inValue.Body = new ApiMefWS.GetPipLocalizacionRequestBody();
            inValue.Body.codigo = codigo;
            return ((ApiMefWS.wsPCMSoap)(this)).GetPipLocalizacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPCMSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPCMSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsPCMSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ofi5.mef.gob.pe/wssnip/wsPCM.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsPCMSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ofi5.mef.gob.pe/wssnip/wsPCM.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsPCMSoap,
            
            wsPCMSoap12,
        }
    }
}
